### ISSUE TITLE
Crash when converting baby drecko anim to scml(?)

### ISSUE THREAD

**Issue by skairunner** [skairunner/kanimal-SE#9] opened 2020-01-13 07:21 UTC
rope_0 is defined twice

**Comment by daviscook477** [comment] 2020-01-13 19:30
I've verified the crash. Since this is an issue with the base game file (or at least some kind of weirdness we don't know how to parse) I'm going to downgrade this error to a warning. And make it still error in strict mode.

This is because I was able to reproduce the seemingly correct behavior of the java kparser by simply having the error be ignored as a warning.

**Comment by daviscook477** [comment] 2020-01-13 19:32
Resolved with https://github.com/skairunner/kanimal-SE/pull/10

**Closed as completed** 2020-01-14 06:16 UTC
